languageCode = 'en-au'
title = "Chenxuan DIY"
theme = 'aether'
relativeURLs = true

[params]
  brand = "Chenxuan DIY"
  description = "DIY website for Chenxuan Rong"
  headshotimg = "profile.jpg"
  rssinmenu = true

[markup]
  [markup.highlight]
    style = "igor"


