languageCode = 'en-au'
title = "Chenxuan DIY"
theme = 'aether'

[params]
  brand = "Chenxuan DIY"
  description = "DIY website for Chenxuan Rong"
  headshotimg = "profile.jpg"

[markup]
  [markup.highlight]
    style = "igor"

[languages]
  [languages.en]
    contentDir = 'content/en'
    baseURL = 'https://diy.rongchenxuan.com/'
    languageName = 'English'
    title = 'Chenxuan DIY'
    weight = 1
  [languages.zh]
    contentDir = 'content/zh'
    baseURL = 'https://maker.rongchenxuan.com'
    languageName = 'Mandarin'
    title = '阿戎的DIY生活'
    weight = 2

